language: python

sudo: false

python:
  - "2.7"
  - "3.5"
  - "nightly" # currently 3.7-dev
  - "pypy"

env:
  - DJANGO_VERSION="1.10.3"
  - DJANGO_VERSION="1.9.11"
  - DJANGO_VERSION="1.8.16"

matrix:
  fast_finish: true
  include:
  - python: "2.7"
    env: DJANGO_VERSION="1.7.11"

install: 
  - pip install -q Django~=$DJANGO_VERSION
  - if [[ DJANGO_VERSION == '1.7'* ]]; then pip install djangorestframework~=2.4.8; fi
  - pip install --editable .[dev]
  - pip install --upgrade pytest

script: 
  - pip freeze
  - pytest --cov=drf_queryfields

after_success:
  - coverage combine
  - coveralls

notifications:
  email: false
