language: python

sudo: false

python:
  - "2.7"
  - "3.6"
  - "pypy"

env:
  - DJANGO_VERSION="1.11.15"
  - DJANGO_VERSION="1.10.8"

matrix:
  fast_finish: true
  include:
  - python: "2.7"
    env: DJANGO_VERSION="1.7.11"
  - python: "3.6"
    env: DJANGO_VERSION="2.0.8"
  - python: "3.6"
    env: DJANGO_VERSION="2.1.0"
  - python: 3.7
    dist: xenial
    sudo: true
    env: DJANGO_VERSION="2.1.0"

install: 
  - pip install -q Django~=$DJANGO_VERSION
  - if [[ $DJANGO_VERSION == '1.7'* ]]; then pip install djangorestframework~=2.4.8; fi
  - pip install --editable .[dev]
  - pip install --upgrade pytest

script: 
  - pip freeze
  - pytest --cov=drf_queryfields

after_success:
  - coverage combine
  - coveralls

notifications:
  email: false
